title: Product
preset: page
num: zero

status:
  draft: true
  listed: true

fields:
  design:
    label: Design by …
    type: text
    width: 3/4
  price:
    type: number
    step: 0.01
    before: €
    width: 1/4
  sizes:
    type: checkboxes
    columns: 3
    default:
      - S
      - M
      - L
      - XL
      - XXL
    options:
      - S
      - M
      - L
      - XL
      - XXL
  link:
    type: url
  description:
    type: textarea

sidebar:
  image:
    extends: sections/image
    template: cover
    min: 1
    image:
      ratio: 1/1
